- hosts: localhost
  connection: local
  become: false
  gather_facts: no

  tasks:
    - name: make sure the package revision of PostgreSQL
      set_fact:
        pg_rev: '15.8-1PGDG.rhel8'
      when: pg_rev is not defined
    - name: make sure pg_rev format is valid
      fail:
        msg: |
          'pg_rev' format must look like '15.8-1PGDG.rhel8'
          Hint - the format has been changed so that it must contains rhel revision
      when: '"rhel" not in pg_rev'
    - name: extract major version number of PostgreSQL
      set_fact:
        pg_major: "{{ pg_rev | regex_replace('^(\\d*)\\..*', '\\1') }}"
    - name: make sure the target distribution major version
      set_fact:
        rhel_major: "{{ pg_rev | regex_replace('.*\\.rhel(\\d)', '\\1') }}"

    - name: Download PostgreSQL {{ pg_rev }} packages
      get_url:
        url="https://yum.postgresql.org/{{ pg_major }}/redhat/rhel-{{ rhel_major }}-x86_64/{{ item }}"
        dest=./roles/postgresql-install/files/
        timeout=60
      with_items:
        - postgresql{{ pg_major }}-libs-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-server-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-docs-{{ pg_rev }}.x86_64.rpm
        - postgresql{{ pg_major }}-contrib-{{ pg_rev }}.x86_64.rpm
