- name: bail if the old configuration is used
  fail:
    msg: |-
      SHAREDDISK_DEV variable in the inventory is obsolated.
      Use the new format of SHAREDDISK_PARTITIONS variable. See the latest inventories/hosts-sample.yml.
  when: SHAREDDISK_DEV is defined

- name: create partitions on the shareddisk for each device
  include_tasks: setup-one-device.yml
  loop: "{{ SHAREDDISK_PARTITIONS | dict2items }}"
  loop_control:
    loop_var: DEVICE
