## # yum -y install targetcli
- name: install targetcli package
  yum:
    name: targetcli
    state: present

## # systemctl enable target.service
## # systemctl start target.service
- name: enable and start target.service
  service:
    name: target.service
    state: started
    enabled: yes

### enable firewall
## # firewall-cmd --permanent --add-service=iscsi-target
## # firewall-cmd --add-service=iscsi-target
#
- name: check if firewalld is enabled
  command: firewall-cmd --state
  changed_when: false
  failed_when: false
  register: firewalld_state

- name: allow iSCSI communication through firewalld (permanent)
  command: firewall-cmd --permanent --add-service=iscsi-target
  register: result
  changed_when: '"ALREADY_ENABLED" not in result.stderr'
  when: firewalld_state.rc == 0

- name: allow iSCSI communication through firewalld (runtime)
  command: firewall-cmd --add-service=iscsi-target
  register: result
  changed_when: '"ALREADY_ENABLED" not in result.stderr'
  when: firewalld_state.rc == 0


## # mkdir /home/iscsi
- name: prepare directory for the fileio backstores
  file:
    path: /home/iscsi
    state: directory

## # targetcli /iscsi create TARGET_IQN
- name: create the iscsi target
  command: >-
    targetcli /iscsi create {{ TARGET_IQN }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already exists" not in result.stderr

### create each LUNs
- name: bail if an old configuration is used
  fail:
    msg: |-
      TARGET_LUN_SIZE variable in the inventory is obsolated.
      Use the new format of TARGET_LUNS variable. See the latest inventories/hosts-sample.yml.
  when: TARGET_LUN_SIZE is defined

## # targetcli /backstores/fileio create LUN.name /home/iscsi/LUN.name.img LUN.size
- name: create the fileio backstore
  command: >-
    targetcli /backstores/fileio create {{ LUN.name }} /home/iscsi/{{ LUN.name }}.img {{ LUN.size }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already exists" not in result.stderr
  with_items: "{{ TARGET_LUNS }}"
  loop_control:
    loop_var: LUN

## # targetcli /iscsi/TARGET_IQN/tpg1/luns create /backstores/fileio/LUN.name
- name: attach the fileio backstore
  command: >-
    targetcli /iscsi/{{ TARGET_IQN }}/tpg1/luns create /backstores/fileio/{{ LUN.name }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already exists" not in result.stderr
  with_items: "{{ TARGET_LUNS }}"
  loop_control:
    loop_var: LUN

## # targetcli saveconfig
- name: save config
  command: >-
    targetcli saveconfig
  register: result
  changed_when: result.rc == 0
  #failed_when: result.rc != 0 and "XXX" not in result.stderr
